---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "^ci"
      - "^build"
      - "^style"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "New Refactorings"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 150
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Dependency Updates"
      regexp: "^.*(feat|fix)\\(deps\\)*:+.*$"
      order: 300
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999
