---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

archives:
  - format: tar.gz
    # This name template makes the OS and Arch compatible with uname and includes the version.
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Wraps the files inside a top-level directory within the archive to prevent tarbombing (Best Practice)
    wrap_in_directory: true
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    # Include all relevant standard documentation arrays using Globs
    files:
      - src: "LICENSE*"
      - src: "README*"
      - src: "CHANGELOG*"

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}-source"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "(?i)^test"
      - "(?i)^chore"
      - "(?i)^ci"
      - "(?i)^build"
      - "(?i)^style"
      - "(?i)^docs"
      - "(?i)^revert"
      - "^Merge pull request"
      - "^Merge remote-tracking branch"
      - "^Merge branch"
      - "merge conflict"
  groups:
    - title: "🚀 Features"
      regexp: "^.*(?i)feat[(\\w)]*:+.*$"
      order: 100
    - title: "🐛 Bug Fixes"
      regexp: "^.*(?i)fix[(\\w)]*:+.*$"
      order: 200
    - title: "⚡️ Performance Improvements"
      regexp: "^.*(?i)perf[(\\w)]*:+.*$"
      order: 300
    - title: "🛠  Refactoring"
      regexp: "^.*(?i)refactor[(\\w)]*:+.*$"
      order: 400
    - title: "📦 Dependency Updates"
      regexp: "^.*(?i)(chore|feat|fix)\\(deps\\):+.*$"
      order: 500
    - title: "🛡️ Security Updates"
      regexp: "^.*(?i)(sec|security)[(\\w)]*:+.*$"
      order: 600
    - title: "📖 Documentation"
      regexp: "^.*(?i)docs[(\\w)]*:+.*$"
      order: 700
    - title: "♻️ Other Work"
      order: 9999
