---
name: GoReleaser

"on":
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
