name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  push:
    branches:
      - main  
  schedule:
    # Automatically run on every Day
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        -
            name: Checkout
            uses: actions/checkout@v4.1.7
            with:
                # [Required] Access token with `workflow` scope.
                token: ${{ secrets.WORKFLOW_SECRET }}
        -
            name: Run GitHub Actions Version Updater
            uses: saadmk11/github-actions-version-updater@v0.8.1
            with:
                # [Required] Access token with `workflow` scope.
                token: ${{ secrets.WORKFLOW_SECRET }}