name: GitHub Actions Version Updater

# Controls when the action will run.
on:
  push:
    branches:
      - "main"
      - "dev"
      - "desktop"
      - "gnome"
      - "plasma"
      - "xfce"
      - "mate"
      - "sway"
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "pr/**"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "desktop"
      - "gnome"
      - "plasma"
      - "xfce"
      - "mate"
      - "sway"
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "pr/**"
  schedule:
    # Automatically run on every Day
    - cron: "30 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.WORKFLOW_SECRET }}
